### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by Noemata** [Aminator9000/DirectX12GameEngine#2]
In AsyncDictionary.cs, I made the following change.  Is this correct in this instance?

#pragma warning disable CS8618 // Non-nullable field is uninitialized. Consider declaring as nullable.
        public event EventHandler<DictionaryChangedEventArgs<TKey, TValue>> ItemAdded;
#pragma warning restore CS8618 // Non-nullable field is uninitialized. Consider declaring as nullable.

Similarly, in the files TransformComponent.cs, Entity.cs, PointerInputSourceBase.cs, KeyboardInputSourceBase.cs and GameWindows.cs, I made a similar change to get the project to build.

**Comment by Aminator** [comment]
It should now be fixed in commit 48c2bb17d3e21c7f20ea2e9f04784d8ef4e73fd9.
