### ISSUE TITLE
Running on HoloLens 2 Emulator crashes system

### ISSUE THREAD

**Issue by Noemata** [Aminator9000/DirectX12GameEngine#7]
This shouldn't happen regardless of a problem with the engine, but I'm experiencing a system crash (blue screen) when trying to run DirectX12CoreWindowApp on the HoloLens 2 emulator.

Have you tried this, or are you running on actual hardware?

**Comment by Noemata** [comment]
Never mind, it's clearly a Microsoft bug!  Again!

If you disable hardware acceleration, it's all working as expected.  Very nice.

You may want to add a note about this problem.  Please close this non-issue.

**Comment by Aminator** [comment]
Interesting, I don't have a real HoloLens, I just tried it with a Windows Mixed Reality headset.
